apiVersion: batch/v1
kind: Job
metadata:
  name: churn-train-job
spec:
  template:
    spec:
      containers:
      - name: churn-train
        image: wikimacd/mlops-churn-train:latest
        volumeMounts:
        - mountPath: /app/data
          name: data-volume
        - mountPath: /app/artifacts
          name: artifacts-volume
        command: ["python", "src/train.py"]
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: artifacts-volume
        persistentVolumeClaim:
          claimName: artifacts-pvc
