apiVersion: v1
kind: Service
metadata:
  name: mlops-churn-train-service
spec:
  selector:
    app: mlops-churn-train
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
